language: node_js
node_js:
- '0.10'
before_install:
- export COMMIT_SHA=`git log -1 --pretty=format:%H`
after_success:
- ! '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && gulp publish-s3'
- ! '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && gulp update-github'
env:
  global:
  - secure: mApa3i/HmtxngKArxwTFAV3lZvhgI+F9Q9c01XoN6tQfkDMskXct4gM2luuUZH4UexuQgP1AowMGA//QYffYgDGD3izFf4farHmb+rSotbHI5vbF+wz3tMdEZyyor4BlQlFl+a+1McVp8QuhxdpLRgfOQrZ/2N+mRBSv9mYo+hw=
  - secure: Xy4YX9E1Rqz9AaIc8rHu4seN5xAecdD7jcDJDqVDDR+LgV9yCI7+oSBp89UL2o4UohmGl11zkLivWaHReQTF6zCtIDE3RBQJYlkaLJwI4ErkR65MNMfQSGWlyD5unjMkgwy506kcVngPCrUUT0HhxbnJWYW+gnhrnx/hNSGu+MQ=
