language: node_js
node_js:
- '0.11'
before_install:
- export COMMIT_SHA=`git log -1 --pretty=format:%H`
script:
- gulp
- ! '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && gulp publish-s3'
after_success:
- ! '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && gulp update-github'
env:
  global:
  - secure: aLUQrHg9IYxLICp2VXsYGtPLGULHDcQKSh523ha1GxFGt6TQFYr5xr/aJnwyC0IDnQRKFFPGIf3VPCk8tSxB/rc5mjFPPJZxKwnAvKN/JY3uTeE4P/rakTa/d5wjDUdwKCDU+RxrupWRnnMkp92+pIDsHp6dTgoVJie17b9WeGQ=
  - secure: WMX0pV3aECnpsBEbxFuZVuZvUyewVDGcp36q2cZo2FtXPeOITIWB8zpF5WCykdITPHmJ8HW0JTN47/8TJBbZPXF6IrTwiJYgykEba3eweE/A9QlHwzfcdFaXYKs4IoLDCylIHJzh7hUBSTg0fXFxp9ZNSAeOACJEkoUGKVnVzXc=
