language: node_js
node_js:
- '0.10'
before_install:
- export COMMIT_SHA=`git log -1 --pretty=format:%H`
after_deploy:
- ! '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && gulp update-github'
env:
  global:
  - secure: aLUQrHg9IYxLICp2VXsYGtPLGULHDcQKSh523ha1GxFGt6TQFYr5xr/aJnwyC0IDnQRKFFPGIf3VPCk8tSxB/rc5mjFPPJZxKwnAvKN/JY3uTeE4P/rakTa/d5wjDUdwKCDU+RxrupWRnnMkp92+pIDsHp6dTgoVJie17b9WeGQ=
  - secure: WMX0pV3aECnpsBEbxFuZVuZvUyewVDGcp36q2cZo2FtXPeOITIWB8zpF5WCykdITPHmJ8HW0JTN47/8TJBbZPXF6IrTwiJYgykEba3eweE/A9QlHwzfcdFaXYKs4IoLDCylIHJzh7hUBSTg0fXFxp9ZNSAeOACJEkoUGKVnVzXc=
  - secure: URteIGdxB4ySnYw6k00HR7nVuYCIeGt7rAiALHcyF3CfA59SZ5lrgs4IJfTM/YvEK/HNl0JX9Ygn4FbU5H6NBb3EE5pKiRRY6e3WHmMBye4iMVnlI8DUF8PYbS6zq9giTAm5+5XPa15JaO8H7fIf7bzCFEuPYQcSkUfA9ZWH3OU=
deploy:
  provider: s3
  access_key_id: AKIAI57KI4WTS3WMRZWQ
  secret_access_key:
    secure: MtlM75JH0hm6wYFp/O1O0kjhqcs8LhXYWDHn1y/ih0a96WKNctlGpSA0ibE3VTyOqe2U2bb74zMiIhDksi/PVQP6MadIGGv3S03VWbbJzSc/s5rQ6+9as81WkMcUnOn4wQhYXd5rtJbiA1NLUkWttg6XuZa9reEl7V7uLLcnDnA=
  bucket: d2lprodcdn
  local-dir: dist
  upload-dir: lib/vui/2.0
  acl: public_read
  skip_cleanup: true
